apiVersion: v1
kind: Service
metadata:
  name: tax-service
  labels:
    app: tax-service
spec:
  type: NodePort
  selector:
    app: tax-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
